# Generated by Django 6.0.1 on 2026-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_herocard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get In Touch', max_length=200)),
                ('description', models.TextField(default="Contact us for any inquiries or support. We're here to help you.")),
                ('image', models.ImageField(default='images/notes/contact.jpg', upload_to='cards/')),
                ('video', models.FileField(blank=True, null=True, upload_to='cards/videos/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FranchisePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Franchise Opportunities', max_length=200)),
                ('description', models.TextField(default='Join our growing network of franchises and be part of our success story.')),
                ('image', models.ImageField(default='images/notes/franchise.jpg', upload_to='cards/')),
                ('video', models.FileField(blank=True, null=True, upload_to='cards/videos/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Home Services', max_length=200)),
                ('description', models.TextField(default='Professional home maintenance and repair services to keep your living space comfortable and well-maintained throughout the year.')),
                ('image', models.ImageField(default='images/notes/home.jpg', upload_to='cards/')),
                ('video', models.FileField(blank=True, null=True, upload_to='cards/videos/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Card',
                'verbose_name_plural': 'Home Page Card',
            },
        ),
        migrations.CreateModel(
            name='PackagesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Packages', max_length=200)),
                ('description', models.TextField(default='Explore our carefully crafted packages designed to meet your every need.')),
                ('image', models.ImageField(default='images/notes/packages.jpg', upload_to='cards/')),
                ('video', models.FileField(blank=True, null=True, upload_to='cards/videos/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HeroCard',
        ),
    ]
