# Generated by Django 5.2.7 on 2026-01-30 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_customuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('dealer', 'Dealer')], default='dealer', max_length=20),
        ),
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('application_type', models.CharField(default='PAINT PROTECTION FILMS', max_length=100)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('installation_date', models.DateField()),
                ('chassis_number', models.CharField(max_length=100)),
                ('vehicle_make_model', models.CharField(max_length=200, verbose_name='Year, Make & Model')),
                ('proof_of_purchase', models.ImageField(upload_to='warranties/proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product')),
            ],
        ),
    ]
