# Generated by Django 6.0.1 on 2026-02-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_customuser_role_warrantyregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(help_text='First line of the banner title', max_length=200, verbose_name='Main Title')),
                ('title2', models.CharField(help_text='Second line of the banner title (colored differently)', max_length=200, verbose_name='Secondary Title')),
                ('description', models.TextField(help_text='Banner description text', verbose_name='Description')),
                ('image', models.ImageField(help_text='Recommended size: 1920x1080px or similar high-quality image', upload_to='banners/%Y/%m/%d/', verbose_name='Banner Image')),
                ('link', models.CharField(blank=True, help_text='Optional custom URL link (overrides product link)', max_length=500, null=True, verbose_name='Custom Link')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide in the banner', verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which slides appear (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='franchisepage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packagespage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
