# Generated by Django 6.0.1 on 2026-02-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_homebannerslide_delete_homepage_alter_contactpage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Franchise Opportunities', max_length=200)),
                ('description', models.TextField(default='Join our growing network of franchises and be part of our success story.')),
                ('image', models.ImageField(default='images/notes/product.jpg', upload_to='product_banner/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FranchisePage',
        ),
    ]
