# Generated by Django 6.0.1 on 2026-02-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_productbanner_delete_franchisepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Packages', max_length=200)),
                ('description', models.TextField(default='Explore our carefully crafted packages designed to meet your every need.')),
                ('image', models.ImageField(default='images/notes/about.jpg', upload_to='about_banner/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PackagesPage',
        ),
    ]
