# Generated by Django 5.2.8 on 2026-02-03 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_advantagebanner_alter_aboutbanner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.RemoveField(
            model_name='warrantyregistration',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='warrantyregistration',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='warrantyregistration',
            name='product',
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='dealer_zip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advantagebanner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='daxdetailingbanner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='daxsolutionsbanner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homebannerslide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siriusbanner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='warrantyproductitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product'),
        ),
        migrations.AddField(
            model_name='warrantyproductitem',
            name='warranty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.warrantyregistration'),
        ),
    ]
