# Generated by Django 5.2.8 on 2026-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_warrantyproductitem_delete_contactpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyproductitem',
            name='product',
            field=models.CharField(default='', max_length=255),
        ),
    ]
